### ISSUE TITLE
Extracting example dependencies to `extra_require`

### ISSUE THREAD

**Issue by cloderic** [kenjyoung/MinAtar#13]
It is possible to install the package directly from GitHub which simplifies a lot using it with a `pip install https://github.com/kenjyoung/MinAtar.git` (I'm actually doing it with poetry with a `poetry add git+https://github.com/kenjyoung/MinAtar.git` but that's mostly equivalent).

However because of the way the setup.py is written this also installs the dependencies for the examples (especially torch which is a behemoth). Would you consider removing them ?

A way to do it simply would be to create an _extra_ section to group the examples dependencies, something like:

```
extras_require = {
     'examples':  ["torch"]
 }
```

I could contribute the change if you think it makes sense.

**Comment by cloderic** [comment]
Done! 

Let me know if something needs to be changed

**Comment by kenjyoung** [comment]
Looks good, thanks!
