### ISSUE TITLE
Docs Request: PyPI addition

### ISSUE THREAD

**Issue by jamesbraza** [kenjyoung/MinAtar#28]
Before I begin, I think a compliment for this repo is that Stanford University is actually using this in its graduate-level [CS234 Reinforcement Learning](http://web.stanford.edu/class/cs234/index.html) homeworks! 🥳 

Students are being instructed to manually `git clone` and `pip install` this repo locally.  At first, I posed directly adding the GitHub repo to `requirements.txt` like so:

```txt
git+ssh://git@github.com/kenjyoung/MinAtar.git
```

I decided to take a look at PyPI, and saw [MinAtar is already published there](https://pypi.org/project/MinAtar/).

The request is: to update the `README.md` to instruct to users to install from PyPI, unless they're going to be contributing.

**Comment by kenjyoung** [comment]
Thanks! I added a note about this to the README as well as a note that the gym interface has recently changed.

**Comment by jamesbraza** [comment]
Sounds good, thank you!  Case closed.
