### ISSUE TITLE
Gym compatible API

### ISSUE THREAD

**Issue by calio** [kenjyoung/MinAtar#4]
It would be really nice to have a Gym compatible API so that existing code can be applied to MinAtar directly.

**Comment by qlan3** [comment]
Please check this: https://github.com/qlan3/gym-games

**Comment by jkterry1** [comment]
It seems like this Gym functionality should be upstreamed into this repo?

**Comment by kenjyoung** [comment]
I added the gym wrapper to the repo as an optional addition. Please let me know if there are any issues with it!

**Comment by vonHartz** [comment]
> I added the gym wrapper to the repo as an optional addition. Please let me know if there are any issues with it!

I just installed MinAtar from Github (Python 3.6.13) and it looks like environments are not automatically registered.
`KeyError: 'MinAtar/Breakout-v1'`

**Comment by kenjyoung** [comment]
I've been using the current gym environment implementation lately and it seems to be working as intended for me. 

Are you using a sufficiently recent version of gym? For example <pip install gym==0.21.0> as mentioned in the README? The issue you are describing sounds vaguely like what I experienced initially when I had an older version of gym installed.

**Comment by vonHartz** [comment]
Wow, thanks for the quick reply!

Sounds like that might be the reason. Dependency-hell forces me to stick with 0.19 for now, but simply re-registering the envs with a prefix worked.
