### ISSUE TITLE
What are the maximum scores achievable in each of the environments?

### ISSUE THREAD

**Issue by floringogianu** [kenjyoung/MinAtar#9]
I've really been enjoying working with MinAtar these couple of weeks and I was wondering, is there any way to figure out what is the maximum score in each of the games? 

I'd like to normalize the scores in some of the plots (and average over games) to get more succinct trends. I also checked the paper but they're not mentioned.

**Comment by kenjyoung** [comment]
Thanks for the interest! 

Unfortunately for such a normalization, the maximum achievable score in most of the games is in principle unbounded. 

Asterix, Seaquest and Space Invaders get progressively harder to a certain point so continuing indefinitely would be difficult but there is no clear maximum achievable score (in space invaders the aliens reset each time they are cleared). In breakout, the difficulty remains constant, but the bricks reset each time they are cleared so a very strong agent could potentially continue indefinitely (or at least until an unfortunate string of sticky actions prevented it from being able to reach the ball in time).

The only game which would have a maximum achievable score is freeway, where the episodes last for a fixed amount of time (this is consistent with freeway in the ALE). In that case, I believe you could upper bound the maximum score by: (time-steps per episode)/((time-steps per movement)*(movements to cross map))=2500/(3*9)=92. However, the agent will not generally be able to achieve this score as it cannot move straight across the map without colliding with a car which sends it back to the start.
